version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sportsbridge
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  ai:
    build: ./ai
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@db:5432/sportsbridge
      - LANGGRAPH_KEY=${LANGGRAPH_KEY}
    depends_on:
      - db
    ports:
      - "8001:8001"
volumes:
  dbdata:
